spring:
  datasource:
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zkr?useUnicode=true&amp&characterEncoding=utf8&amp&serverTimezone=GMT%2b8

mybatis:
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    com.gyb.demo.dao: debug

